# Generated by Django 4.2.28 on 2026-04-21 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TN')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('cnam_affiliated', models.BooleanField(default=False)),
                ('cnam_code', models.CharField(blank=True, max_length=50, null=True)),
                ('accreditation', models.TextField(blank=True, null=True)),
                ('opening_hours', models.JSONField(default=dict, help_text='Format: {"lundi": ["08:00-12:00", "14:00-18:00"], ...}')),
                ('appointment_duration', models.PositiveIntegerField(default=30, help_text='Durée par défaut en minutes')),
                ('timezone', models.CharField(default='Africa/Tunis', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cabinet_logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cabinet_banners/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cabinet Médical',
                'verbose_name_plural': 'Cabinets Médicaux',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('cnam_code', models.CharField(blank=True, max_length=50, null=True)),
                ('consultation_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Liste des certifications (JSON)')),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('teleconsultation_available', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('cabinets', models.ManyToManyField(related_name='doctors', to='cabinets.cabinet')),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.CreateModel(
            name='DoctorUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacances'), ('training', 'Formation'), ('emergency', 'Urgence'), ('conference', 'Conférence'), ('other', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='cabinets.doctor')),
            ],
            options={
                'verbose_name': 'Indisponibilité du Médecin',
                'verbose_name_plural': 'Indisponibilités des Médecins',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=15, help_text='Durée du créneau en minutes')),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='cabinets.doctor')),
            ],
            options={
                'verbose_name': 'Disponibilité du Médecin',
                'verbose_name_plural': 'Disponibilités des Médecins',
                'ordering': ['doctor', 'day', 'start_time'],
            },
        ),
    ]
