# Generated by Django 4.2.28 on 2026-04-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='users.medicalspecialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.city'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cabinets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='secretaries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'secretary'}, related_name='managed_cabinets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='specialties',
            field=models.ManyToManyField(related_name='cabinets', to='users.medicalspecialty'),
        ),
        migrations.AddIndex(
            model_name='doctorunavailability',
            index=models.Index(fields=['doctor', 'start_datetime'], name='cabinets_do_doctor__69cad5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='cabinets_do_special_3f537d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['rating'], name='cabinets_do_rating_095389_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinet',
            index=models.Index(fields=['city', 'is_active'], name='cabinets_ca_city_id_861337_idx'),
        ),
        migrations.AddIndex(
            model_name='cabinet',
            index=models.Index(fields=['cnam_affiliated'], name='cabinets_ca_cnam_af_3a939d_idx'),
        ),
    ]
