# Generated by Django 4.2.28 on 2026-09-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='ai_chat_message_v2',
        ),
    ]
