# Generated by Django 4.2.28 on 2026-09-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_chatmessage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
    ]
