# Generated by Django 4.2.28 on 2026-04-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinets', '0001_initial'),
        ('users', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('in_progress', 'En consultation'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='waiting', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Urgence'), ('child', 'Enfant'), ('senior', 'Personne âgée'), ('pregnant', 'Femme enceinte')], default='normal', max_length=20, verbose_name='Priorité')),
                ('reason', models.CharField(choices=[('consultation', 'Consultation générale'), ('follow_up', 'Suivi / Contrôle'), ('emergency', 'Urgence'), ('vaccination', 'Vaccination'), ('analysis', "Résultat d'analyses"), ('certificate', 'Certificat médical'), ('prescription_renewal', "Renouvellement d'ordonnance"), ('other', 'Autre')], default='consultation', max_length=30, verbose_name='Motif')),
                ('reason_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Détails du motif')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position dans la file')),
                ('estimated_wait_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name="Temps d'attente estimé (min)")),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Heure d'arrivée")),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'appel")),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début de consultation')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de consultation')),
                ('actual_wait_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name="Temps d'attente réel (min)")),
                ('consultation_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de consultation (min)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('doctor_notes', models.TextField(blank=True, null=True, verbose_name='Notes du médecin')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_queue_entry', to='appointments.appointment', verbose_name='Rendez-vous lié')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_queue_entries', to='cabinets.cabinet', verbose_name='Cabinet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queue_entries', to='cabinets.doctor', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queue_entries', to='users.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': "Entrée file d'attente",
                'verbose_name_plural': "File d'attente",
                'ordering': ['position', 'joined_at'],
                'indexes': [models.Index(fields=['doctor', 'status', 'joined_at'], name='waiting_que_doctor__55e539_idx'), models.Index(fields=['patient', 'status'], name='waiting_que_patient_a2996b_idx'), models.Index(fields=['cabinet', 'status'], name='waiting_que_cabinet_8a0c1e_idx'), models.Index(fields=['status', 'priority'], name='waiting_que_status_e727cf_idx')],
            },
        ),
    ]
