# Generated by Django 4.2.28 on 2026-04-21 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'dicom', 'tiff'])])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('lab_result', 'Résultat de laboratoire'), ('scan', 'Scanner/IRM'), ('xray', 'Radiographie'), ('other', 'Autre')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce Jointe Médicale',
                'verbose_name_plural': 'Pièces Jointes Médicales',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('diagnosis_code', models.CharField(blank=True, help_text='Code CIM-10', max_length=20, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('emergency', 'Urgence')], default='medium', max_length=20)),
                ('confidentiality_level', models.CharField(choices=[('normal', 'Normale'), ('sensitive', 'Sensible'), ('highly_sensitive', 'Très Sensible')], default='normal', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='cabinets.doctor')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('tablet', 'Comprimé'), ('capsule', 'Capsule'), ('liquid', 'Liquide'), ('injection', 'Injection'), ('cream', 'Crème'), ('ointment', 'Pommade'), ('other', 'Autre')], default='tablet', max_length=50)),
                ('frequency', models.CharField(help_text='Ex: 3 fois par jour', max_length=100)),
                ('duration', models.CharField(help_text='Ex: 7 jours', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Quantité totale')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('with_meals', models.BooleanField(default=False)),
                ('before_meals', models.BooleanField(default=False)),
                ('after_meals', models.BooleanField(default=True)),
                ('is_generic_allowed', models.BooleanField(default=True)),
                ('refills_allowed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_electronic', models.BooleanField(default=False)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
    ]
