# Generated by Django 4.2.28 on 2026-08-02 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cabinets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('unpaid', 'Non Payé'), ('paid', 'Payé')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte Bancaire'), ('cnam', 'CNAM'), ('insurance', 'Assurance')], max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispensation / Vente',
                'verbose_name_plural': 'Dispensations / Ventes',
                'ordering': ['-dispensation_date'],
            },
        ),
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Ligne de dispensation',
                'verbose_name_plural': 'Lignes de dispensation',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('active_ingredient', models.CharField(max_length=200, verbose_name='Principe actif')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage (ex: 500mg, 5ml)')),
                ('form', models.CharField(choices=[('tablet', 'Comprimé'), ('capsule', 'Gélule'), ('syrup', 'Sirop'), ('injection', 'Injection'), ('cream', 'Crème/Pommade'), ('drops', 'Gouttes'), ('spray', 'Spray'), ('other', 'Autre')], max_length=20, verbose_name='Forme galénique')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('cnam_refunded', models.BooleanField(default=False, verbose_name='Remboursable CNAM')),
                ('cnam_refund_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de remboursement CNAM (%)')),
                ('requires_prescription', models.BooleanField(default=True, verbose_name='Sur ordonnance')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pharmacie')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TN', verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_on_duty', models.BooleanField(default=False, verbose_name='Garde actuelle')),
                ('opening_hours', models.JSONField(default=dict, verbose_name="Horaires d'ouverture")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/%Y/%m/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='users.city')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('dispensed', 'Délivrée'), ('partially_dispensed', 'Délivrée partiellement'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('paper_prescription_scan', models.ImageField(blank=True, null=True, upload_to='prescription_scans/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescriptions', to='cabinets.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='users.patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_instruction', models.CharField(max_length=255, verbose_name='Posologie (ex: 1 comprimé x3/jour)')),
                ('quantity_prescribed', models.PositiveIntegerField(verbose_name='Quantité prescrite')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
                'verbose_name_plural': "Lignes d'ordonnance",
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('buying_price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat")),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de lot')),
                ('expiry_date', models.DateField(verbose_name='Date de péremption')),
                ('last_restocked_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='pharmacy.medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pharmacy.pharmacy')),
            ],
            options={
                'verbose_name': 'Stock Pharmacie',
                'verbose_name_plural': 'Stocks Pharmacies',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='pharmacy_me_name_46a660_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['active_ingredient'], name='pharmacy_me_active__3eaa78_idx'),
        ),
        migrations.AddField(
            model_name='dispensationitem',
            name='dispensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispensation'),
        ),
        migrations.AddField(
            model_name='dispensationitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='dispensationitem',
            name='stock_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacystock'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_dispensations', to='users.patient'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='pharmacist',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.prescription'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacystock',
            unique_together={('pharmacy', 'medication')},
        ),
    ]
