# Generated by Django 4.2.28 on 2026-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='active_ingredient',
            field=models.CharField(blank=True, default='Inconnu', max_length=200, verbose_name='Principe actif'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(choices=[('tablet', 'Comprimé'), ('capsule', 'Gélule'), ('syrup', 'Sirop'), ('injection', 'Injection'), ('cream', 'Crème/Pommade'), ('drops', 'Gouttes'), ('spray', 'Spray'), ('other', 'Autre')], default='tablet', max_length=20, verbose_name='Forme galénique'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage_instruction',
            field=models.CharField(max_length=255, verbose_name='Posologie'),
        ),
    ]
