# Generated by Django 4.2.28 on 2026-09-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taille en mètres (ex: 1.80)', max_digits=5, null=True),
        ),
    ]
