# Generated by Django 4.2.28 on 2026-03-01 01:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('document_type', models.CharField(choices=[('diploma', 'Diplôme / Doctorat'), ('certificate', 'Certificat / Attestation'), ('lab_result', "Résultat d'analyse"), ('prescription', 'Ordonnance'), ('medical_record', 'Dossier médical'), ('radio', 'Radiographie / Imagerie'), ('other', 'Autre document')], default='other', max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document utilisateur',
                'verbose_name_plural': 'Documents utilisateur',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='users_userd_user_id_6ca0f5_idx'), models.Index(fields=['is_verified'], name='users_userd_is_veri_28c91f_idx')],
            },
        ),
    ]
