# Generated by Django 4.2.28 on 2026-03-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('semiannual', 'Semestriel'), ('yearly', 'Annuel')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('doctor', 'Médecin'), ('lab_staff', 'Personnel de Laboratoire'), ('patient', 'Patient'), ('secretary', 'Secrétaire'), ('pharmacist', 'Pharmacien')], default='patient', max_length=20),
        ),
    ]
