# Generated by Django 4.2.28 on 2026-04-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_by_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='laboratories.laboratory'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='laboratories.labtestrequest'),
        ),
    ]
