# Generated by Django 4.2.28 on 2026-04-21 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TN')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=100, null=True)),
                ('accreditation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cnam_affiliated', models.BooleanField(default=False)),
                ('cnam_code', models.CharField(blank=True, max_length=50, null=True)),
                ('services_offered', models.JSONField(default=list, help_text='Services offerts (liste JSON)')),
                ('opening_hours', models.JSONField(default=dict)),
                ('sample_collection_hours', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='Africa/Tunis', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lab_logos/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laboratoire',
                'verbose_name_plural': 'Laboratoires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=dict, help_text='Format: {"test_code": {"value": "X", "unit": "Y", "normal_range": "Z"}, ...}')),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='lab_results/%Y/%m/%d/')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('critical_finding', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Résultat d'Analyse",
                'verbose_name_plural': "Résultats d'Analyses",
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('hematology', 'Hématologie'), ('biochemistry', 'Biochimie'), ('microbiology', 'Microbiologie'), ('immunology', 'Immunologie'), ('hormones', 'Hormones'), ('urinalysis', "Analyse d'urine"), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('turnaround_time', models.PositiveIntegerField(help_text='Délai en heures')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cnam_coverage', models.BooleanField(default=False)),
                ('cnam_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': "Type d'Analyse",
                'verbose_name_plural': "Types d'Analyses",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'Stat (Immédiat)')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Demandé'), ('sample_collected', 'Prélèvement Effectué'), ('in_progress', "En Cours d'Analyse"), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='requested', max_length=20)),
                ('clinical_history', models.TextField(blank=True, null=True)),
                ('diagnosis_suspected', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='cabinets.doctor')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='laboratories.laboratory')),
            ],
            options={
                'verbose_name': "Demande d'Analyse",
                'verbose_name_plural': "Demandes d'Analyses",
                'ordering': ['-request_date'],
            },
        ),
    ]
