# Generated by Django 4.2.28 on 2026-04-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='users.patient'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sample_collected_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lab_staff', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='tests',
            field=models.ManyToManyField(related_name='requests', to='laboratories.labtesttype'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='analyzed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'lab_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratories.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.city'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'lab_staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='secretaries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'secretary'}, related_name='managed_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='laboratories', to='users.medicalspecialty'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['patient', 'request_date'], name='laboratorie_patient_4e8a87_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['status'], name='laboratorie_status_8ddbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['priority'], name='laboratorie_priorit_b9dcf0_idx'),
        ),
    ]
