# Generated by Django 4.2.28 on 2026-08-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='lab_banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
