# Generated by Django 4.2.28 on 2026-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0003_laboratory_banner_laboratory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte Bancaire'), ('online', 'Paiement en ligne (Stripe)'), ('cnam', 'CNAM'), ('insurance', 'Assurance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non Payé'), ('paid', 'Payé')], default='unpaid', max_length=20),
        ),
    ]
