# Generated by Django 4.2.28 on 2026-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=30, help_text='Durée en minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('confirmed', 'Confirmé'), ('in_progress', 'En Cours'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('no_show', 'Non Présenté')], default='scheduled', max_length=20)),
                ('is_teleconsultation', models.BooleanField(default=False)),
                ('consultation_type', models.CharField(choices=[('first', 'Première consultation'), ('followup', 'Consultation de suivi'), ('emergency', 'Urgence'), ('routine', 'Consultation de routine')], default='routine', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('patient', 'Patient a annulé'), ('doctor', 'Médecin a annulé'), ('emergency', 'Urgence médicale'), ('weather', 'Mauvais temps'), ('other', 'Autre')], max_length=20, null=True)),
                ('cancellation_notes', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_sent_24h', models.BooleanField(default=False)),
                ('reminder_sent_1h', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_time'],
            },
        ),
    ]
